"use strict";

window.ESCROWLESS_CONFIG = Object.freeze({
  companyName: "EscrowLess, Inc.",
  environment: "public-demo",
  release: "8.0.0-market-estimator-fee-model",
  demoOnly: true,
  mockDataOnly: true,
  publicDemoOnly: true,
  allowTemporaryMockEdits: true,
  allowMockProviderCalls: true,
  realWorldEffectsDisabled: true,
  features: Object.freeze({
    accountCreation: false,
    authentication: false,
    formSubmission: false,
    recordPersistence: false,
    fileUploads: false,
    emailOrMessaging: false,
    paymentsOrEscrow: false,
    bindingContracts: false,
    supabase: false,
    externalApis: false,
    analytics: false,
  }),
  productionCapabilities: Object.freeze({
    realOffers: false,
    persistentStorage: false,
    fileUploads: false,
    payments: false,
    eSignature: false,
    identityVerification: false,
    titleOrders: false,
    escrowActivity: false,
    remoteNotarization: false,
    eClosing: false,
    eRecording: false,
    email: false,
    mlsAccess: false,
    lending: false,
    insurance: false,
    legalServices: false,
    brokerageServices: false,
  }),
  approvalGates: Object.freeze({
    ceo: false,
    supervisingBroker: false,
    legal: false,
    compliance: false,
    security: false,
    vendorManagement: false,
  }),
  providers: Object.freeze({
    identity: Object.freeze({ mode: "mock", credentialState: "none" }),
    listings: Object.freeze({ mode: "mock", credentialState: "none" }),
    eSignature: Object.freeze({ mode: "mock", credentialState: "none" }),
    documentVault: Object.freeze({ mode: "mock", credentialState: "none" }),
    earnestMoney: Object.freeze({ mode: "mock", credentialState: "none" }),
    titleSettlement: Object.freeze({ mode: "mock", credentialState: "none" }),
    remoteNotary: Object.freeze({ mode: "mock", credentialState: "none" }),
    eClosing: Object.freeze({ mode: "mock", credentialState: "none" }),
    eRecording: Object.freeze({ mode: "mock", credentialState: "none" }),
    contactDelivery: Object.freeze({ mode: "mock", credentialState: "none" }),
  }),
});
